language: python
sudo: required
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ansible

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script: nosetests